use crate::callback;
use crate::config::{self, IssuerType};
use crate::store;
use anyhow::Result;
use openidconnect::core::{CoreAuthenticationFlow, CoreClient, CoreProviderMetadata};
use openidconnect::{
    AccessToken, AuthorizationCode, ClientId, ClientSecret, CsrfToken, EndpointMaybeSet,
    EndpointNotSet, EndpointSet, OAuth2TokenResponse, RedirectUrl, RefreshToken, Scope,
    TokenResponse,
};
use openidconnect::{IssuerUrl, Nonce, reqwest};
use tracing::info;


/// The concrete client type returned by `CoreClient::from_provider_metadata`.
///
/// `openidconnect` encodes which endpoints are available at the type level (the
/// "type-state" pattern). After discovery the authorization endpoint is set, the
/// token and userinfo endpoints are optional, and the remaining ones are unset.
/// Naming this concrete type lets both flows share a single discovered client.
/// The redirect URI is *not* part of the type state, so it is attached later by
/// cloning the client (see `run_authorization_code_flow`).
type DiscoveredClient = CoreClient<
    EndpointSet,      // HasAuthUrl
    EndpointNotSet,   // HasDeviceAuthUrl
    EndpointNotSet,   // HasIntrospectionUrl
    EndpointNotSet,   // HasRevocationUrl
    EndpointMaybeSet, // HasTokenUrl
    EndpointMaybeSet, // HasUserInfoUrl
>;


/// Discover the OIDC provider metadata and build the client, so that both the
/// Refresh Token and the Authorization Code flows share the same HTTP client and
/// OAuth client instead of each constructing their own.
async fn discover() -> Result<(reqwest::Client, DiscoveredClient)> {

    // Access the global configuration
    let cfg = config::get();

    info!("Discovering OIDC provider metadata for provider '{}'", cfg.issuer_type);

    let http_client = reqwest::Client::new();
    let issuer_url = IssuerUrl::new(cfg.issuer_url.clone())?;
    let provider_metadata = CoreProviderMetadata::discover_async(issuer_url, &http_client).await?;

    // Since this app is an OAuth2 confidential client, we send the client secret
    // along with the client identifier produced by the Authorization Server.
    let oidc_client = CoreClient::from_provider_metadata(
        provider_metadata,
        ClientId::new(cfg.client_id.clone()),
        Some(ClientSecret::new(cfg.client_secret.clone())),
    );

    Ok((http_client, oidc_client))
}


/// Attempt the Refresh Token flow using a token persisted by a previous run.
///
/// Returns an error (so the caller can fall back to the Authorization Code flow)
/// when no refresh token is stored or when the Authorization Server rejects it.
async fn run_refresh_token_flow(
    http_client: &reqwest::Client,
    oidc_client: &DiscoveredClient,
) -> Result<AccessToken> {
    info!("Attempting the Refresh Token flow");

    let Some(refresh_token) = store::load_refresh_token().await? else {
        anyhow::bail!("no refresh token stored");
    };

    let token_response = oidc_client
        // `exchange_refresh_token` returns a `Result<RefreshTokenRequest, ConfigurationError>`
        // (the token endpoint URL may be missing), so unwrap it before requesting.
        .exchange_refresh_token(&RefreshToken::new(refresh_token))?
        .request_async(http_client)
        .await?;

    // Some providers rotate the refresh token on each use; persist the new one.
    if let Some(new_refresh_token) = token_response.refresh_token() {
        store::save_refresh_token(new_refresh_token.secret()).await?;
    }

    Ok(token_response.access_token().clone())
}


async fn run_authorization_code_flow(
    http_client: &reqwest::Client,
    oidc_client: &DiscoveredClient,
) -> Result<AccessToken> {

    // Access the global configuration
    let cfg = config::get();

    // The OAuth "state" parameter is an opaque value generated by this OAuth Client Application
    // to prevent Cross-Site Request Forgery (CSRF) attacks on the client callback endpoint
    // (see RFC 6749 Section 10.12). The Auth Server will reply the same value back, still
    // as "state" parameter on the redirect location along with the authorization "code".
    let csrf_token = CsrfToken::new_random();

    // TODO Explain why we use a nonce
    let nonce = Nonce::new_random();

    // Spawn the ephemeral `/callback` HTTP endpoint
    let (callback_url, oauth_code_rx) =  callback::spawn_endpoint(&csrf_token).await?;

    // The redirect URI is only relevant to this flow, so we clone the discovered
    // client and attach it without affecting the shared instance.
    let redirect_uri = RedirectUrl::new(callback_url)?;
    let oidc_client = oidc_client.clone().set_redirect_uri(redirect_uri);

    let flow = CoreAuthenticationFlow::AuthorizationCode;

    // The `openid` scope is added automatically by the underlying library
    // (see CoreClient::authorize_url); here we only append the scopes
    // configured by this client application.

    // Generate the authorize URL, applying the provider-specific quirks that
    // determine how a refresh token is requested.
    // TODO Optionally .set_pkce_challenge(pkce_challenge)
    let mut request = oidc_client
        .authorize_url(
            flow,
            || csrf_token,
            || nonce
        )
        .add_scopes(cfg.scopes.iter().cloned().map(Scope::new));

    match cfg.issuer_type {
        // Google is the outlier: `access_type=offline` asks for a refresh token
        // and `prompt=consent` forces the consent screen so a refresh token is
        // (re)issued on every authorization. Google does not use the standard
        // `offline_access` scope.
        IssuerType::Google => {
            request = request
                .add_extra_param("access_type", "offline")
                .add_extra_param("prompt", "consent");
        }
        // All other supported providers request a refresh token via the standard
        // `offline_access` scope.
        _ => {
            request = request.add_scope(Scope::new("offline_access".to_string()));
        }
    }

    let (authorize_url, _, nonce) = request.url();

    info!("Opening your default browser with the authorize URL {}", authorize_url);
    // TODO webbrowser::open(authorize_url.as_str())?;

    // Await for the authorization code to be sent by the Authorization Server
    // to our ephemeral `/callback` endpoint. The outer `?` handles a dropped
    // channel (RecvError); the inner `?` propagates the authorization failure
    // reported by the callback endpoint (e.g. the user denied consent).

    let oauth_code_str = oauth_code_rx.await??;
    info!("OAuth code is: {}", oauth_code_str);

    // Exchange the authorization code with the access, id and refresh tokens
    let code = AuthorizationCode::new(oauth_code_str);
    let token_response =
        oidc_client
            // `exchange_code` returns a `Result<CodeTokenRequest, ConfigurationError>`
            // (the token endpoint URL may be missing), so unwrap it before requesting.
            .exchange_code(code)?
            // TODO Optionally .set_pkce_verifier(pkce_verifier)
            .request_async(http_client)
            .await?;


    // Validate the ID token
    if let Some(id_token) = token_response.id_token() {
        let verifier = oidc_client.id_token_verifier();
        let claims = id_token.claims(&verifier, &nonce)?;
        info!("ID token verified; subject = {}", claims.subject().as_str());
    }

    // Persist the refresh token so the next run can skip the browser round-trip.
    if let Some(refresh_token) = token_response.refresh_token() {
        store::save_refresh_token(refresh_token.secret()).await?;
    }

    Ok(token_response.access_token().clone())
}


///
/// Get an access token by attempting the following OAuth2 flows in order:
///
///  1. refresh token
///  2. authorization code
///
pub async fn get_access_token() -> Result<AccessToken> {

    info!("Getting an OAuth2 access token ...");

    let (http_client, oidc_client) = discover().await?;

    match run_refresh_token_flow(&http_client, &oidc_client).await {
        Ok(access_token) => {
            info!("Access token obtained via the Refresh Token flow");
            Ok(access_token)
        }
        Err(err) => {
            info!("Refresh Token flow unavailable ({}); falling back to the Authorization Code flow", err);
            run_authorization_code_flow(&http_client, &oidc_client).await
        }
    }
}


